export const ANALYZE = 'ANALYZE';

export const ANALYSIS_STATUS_WAITING = 'ANALYSIS_STATUS_WAITING';
export const ANALYSIS_STATUS_PENDING = 'ANALYSIS_STATUS_PENDING';
export const ANALYSIS_STATUS_SUCCEEDED = 'ANALYSIS_STATUS_SUCCEEDED';
export const ANALYSIS_STATUS_FAILED = 'ANALYSIS_STATUS_FAILED';

export const SORT = 'SORT';
export const USE = 'USE';
export const STOP_USING = 'STOP_USING';
export const SEARCH = 'SEARCH';

export const FETCH_LIBRARIES_SUCCEEDED = 'FETCH_LIBRARIES_SUCCEEDED';
