export const ANALYSIS_POLL_INTERVAL = 2000;

export const ANALYZE = 'ANALYZE';
export const ANALYSIS_STARTED = 'ANALYSIS_STARTED';
export const ANALYSIS_SUCCEEDED = 'ANALYSIS_SUCCEEDED';
export const ANALYSIS_FAILED = 'ANALYSIS_FAILED';

export const SORT = 'SORT';
export const USE = 'USE';
export const STOP_USING = 'STOP_USING';
export const SEARCH = 'SEARCH';
export const FETCH_LIBRARIES_SUCCEEDED = 'FETCH_LIBRARIES_SUCCEEDED';
