language: node_js
node_js:
  - "7"
cache: yarn
script:
  - npm test
  - npm run build
deploy:
  - provider: heroku
    app: libsizes
    skip_cleanup: true
    api_key:
      secure: $HEROKU_API_KEY
  - provider: firebase
    skip_cleanup: true
    api_key:
      secure: $FIREBASE_TOKEN
