PostgreSQL:
  container_name: libsizes-postgresql
  restart: always
  image: sameersbn/postgresql:9.5-3
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=user
    - DB_PASS=development
    - DB_NAME=libsizes
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
