module.exports = {
  ANALYSIS_REQUESTED: 'ANALYSIS_REQUESTED',
  ANALYSIS_STARTED: 'ANALYSIS_STARTED',
  ANALYSIS_SUCCEEDED: 'ANALYSIS_SUCCEEDED',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  ANALYSIS_PROGRESSED: 'ANALYSIS_PROGRESSED',
  ANALYSIS_UPDATED: 'ANALYSIS_UPDATED'
};
